const ADD_COMICS = "ADD_COMICS";

const LOADING_ERROR = "LOADING_ERROR";
const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
const LOADING_SUCCESS = "LOADING_SUCCESS";

export { ADD_COMICS, LOADING_ERROR, LOADING_IN_PROGRESS, LOADING_SUCCESS };
