const APPEND_COMICS = "APPEND_COMICS";

const SET_FILTER = "SET_FILTER";

const LOADING_ERROR = "LOADING_ERROR";
const LOADING_IN_PROGRESS = "LOADING_IN_PROGRESS";
const LOADING_SUCCESS = "LOADING_SUCCESS";

export { APPEND_COMICS, SET_FILTER, LOADING_ERROR, LOADING_IN_PROGRESS, LOADING_SUCCESS };
